apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-efs-pvc
spec: 
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 storageClassName: efs-sc
 resources:
   requests:
     storage: 5Gi

